version: 0.2

env:
  variables:
    src: s3://#{variables.bucket}/#{variables.key}

phases:
  build:
    commands:
      - echo "${AWS_REGION}" "${src}" "#{codepipeline.PipelineExecutionId}"
      - aws s3 cp ${src} app.zip
artifacts:
  files:
    - app.zip