version: 0.2
phases:
  build:
    commands:
      - aws s3 cp s3://elasticbeanstalk-samples-${AWS_REGION}/java-sample-app.zip java-sample-app.zip
      - unzip java-sample-app.zip -d java-sample-app.d
      - sed -i "4s/Elastic Beanstalk/Elastic Beanstalk @ Build ${CODEBUILD_BUILD_NUMBER-???}/" java-sample-app.d/src/main/resources/index.html
      - sed -i "/maven-assembly-plugin/ a <version>2.2</version>" java-sample-app.d/pom.xml
      - cd java-sample-app.d && mvn assembly:assembly -DdescriptorId=jar-with-dependencies
artifacts:
  base-directory: java-sample-app.d/target
  files:
    - sample-app-1.0-jar-with-dependencies.jar

# CodeDeploy for ElasticBeanstalk expects a directory of files to deploy, not a ZIP file. Apparently it will ZIP it up itself.
# Specifically the Buildfile and Procfile must be in the root of the artifacts listed here.

# The docs imply that one can provide just an uber-JAR. We shall see.