AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with S3 Source, CodeBuild, and S3 Deploy

Parameters:
  applicationStack:
    Type: String
    Description: Name of the Elastic Beanstalk application stack
  sourceConnectionArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: ARN of the CodeStar Connection to the source repository
    Default: /github/codestar
  sourceRepository:
    Type: String
    Description: Repository name
    Default: nickbreen/ci-cd-beanstalk

Resources:

  artifactStore:
    Type: AWS::S3::Bucket

  codeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt codeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_LAMBDA_1GB
        Image: aws/codebuild/amazonlinux-aarch64-lambda-standard:corretto11
        Type: ARM_LAMBDA_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - aws s3 cp s3://elasticbeanstalk-samples-${AWS_REGION}/java-sample-app.zip java-sample-app.zip
                - unzip java-sample-app.zip -d java-sample-app.d
                - sed -i "4s/Elastic Beanstalk/Elastic Beanstalk @ Build ${CODEBUILD_BUILD_NUMBER-???}/" java-sample-app.d/src/main/resources/index.html
                - cd java-sample-app.d && mvn assembly:assembly -DdescriptorId=jar-with-dependencies
          artifacts:
            base-directory: java-sample-app.d
            files:
              - target/sample-app-1.0-jar-with-dependencies.jar

  codePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt codePipelineRole.Arn
      PipelineType: V2
      RestartExecutionOnUpdate: true
      ArtifactStore:
        Type: S3
        Location: !Ref artifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: main
                ConnectionArn: !Ref sourceConnectionArn
                DetectChanges: false
                FullRepositoryId: !Ref sourceRepository
                OutputArtifactFormat: CODE_ZIP
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref codeBuild
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ElasticBeanstalk
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName:
                  Fn::ImportValue:
                    !Sub "${applicationStack}-application"
                EnvironmentName:
                  Fn::ImportValue:
                    !Sub "${applicationStack}-environment"

  codePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: ElasticBeanstalkDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                Resource: "*"
        - PolicyName: CodeStarPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Ref sourceConnectionArn

  codeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*