AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for creating a CI/CD pipepline for an Elastic Beanstalk application in the Default VPC

Parameters:
  ebSourceBundleBucket:
    Type: String
    Description: S3 bucket where the Elastic Beanstalk source bundle is stored
    Default: elasticbeanstalk-samples
  ebSourceBundleKey:
    Type: String
    Description: S3 key where the Elastic Beanstalk source bundle is stored
    Default: java-sample-app.zip

Outputs:
  URL:
    Description: URL of the Elastic Beanstalk environment
    Value: !GetAtt ebEnvironment.EndpointURL

Resources:

  ebApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Sample Java application

  ebApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref ebApplication
      Description: Sample Java application version
      SourceBundle:
        S3Bucket: !Sub "${ebSourceBundleBucket}-${AWS::Region}"
        S3Key: !Ref ebSourceBundleKey

  ebEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ebApplication
      Description: Sample Java environment
      #SolutionStackName: "64bit Amazon Linux 2023 v4.2.4 running Corretto 21"
      #SolutionStackName: "64bit Amazon Linux 2023 v4.2.4 running Corretto 8"
      SolutionStackName: "64bit Amazon Linux 2023 v4.2.4 running Corretto 11"
      VersionLabel: !Ref ebApplicationVersion
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref ebInstanceProfile
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t4g.nano,t4g.micro
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: PORT
          Value: "5000"

  ebInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier

  ebInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ebInstanceRole